cmsStage -f ../data/ntuples/preselected/DYJets_1.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_2.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_3.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_4.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_5.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_6.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_7.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_8.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_9.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_10.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_11.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_12.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_13.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_14.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_15.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_16.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_17.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_18.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_19.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_20.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_21.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_22.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_23.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_24.root /store/user/veelken/Lucia/preselected_V3/
cmsStage -f ../data/ntuples/preselected/DYJets_25.root /store/user/veelken/Lucia/preselected_V3/

#cmsStage -f ../data/ntuples/preselected/TT_1.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/TT_2.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/TT_3.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/TT_4.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/TT_5.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/TT_6.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/TT_7.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/TT_8.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/TT_9.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/TT_10.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/TT_11.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/TT_12.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/TT_13.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/TT_14.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/TT_15.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/DY1Jets.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/DY2Jets.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/DY3Jets.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/DY4Jets.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/EWKWMinus.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/EWKWPlus.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/EWKZToLL.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/GluGluHToTauTau_M125.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/ST_tW_antitop.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/ST_tW_top.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/ST_t_antitop.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/ST_t_top.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/SingleMuon.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/VBFHToTauTau_M125.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/W1Jets.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/W2Jets.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/W3Jets.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/W4Jets.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/WJets.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/WW.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/WZJets.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/WZTo1L1Nu2Q.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/WZTo1L3Nu.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/WZTo2L2Q.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/ZZTo2L2Q.root /store/user/veelken/Lucia/preselected_V3/
#cmsStage -f ../data/ntuples/preselected/ZZTo4L.root /store/user/veelken/Lucia/preselected_V3/
